### ISSUE TITLE
How to handle co-authors

### ISSUE THREAD

**Issue by ctuffli** [freebsd/freebsd-papers#117]
I want to add a talk I co-presented at EuroBSDCon 2021 and need some advice on how to name the files/directories as there are two last names. Do I just pick one of the author last names or add both? E.g.
`tuffli-smart_Update_A_Permissively_Licensed_Alternative_to_smartctl`
or
`dexter-tuffli-smart_Update_A_Permissively_Licensed_Alternative_to_smartctl`

(https://2021.eurobsdcon.org/home/speakers/#smart if it matters)

**Comment by ppaeps** [comment]
Either will do. 😄 

Thank you!

**Comment by ctuffli** [comment]
OK, dug around and found an example. See #118

**Comment by ppaeps** [comment]
Thanks for your submission.  I've merged your pull request.
