### ISSUE TITLE
Add talks from vBSDCon 2015

### ISSUE THREAD

**Issue by allanjude** [freebsd/freebsd-papers#36]
https://www.youtube.com/watch?v=Gd1rxMSLMYc
https://www.youtube.com/watch?v=SNwQZURgqls
https://www.youtube.com/watch?v=JgsBnLFfZaE
https://www.youtube.com/watch?v=73M7h56Dsas
https://www.youtube.com/watch?v=qXOZmDoy2Co
https://www.youtube.com/watch?v=9BcdRHNTdf4

**Comment by allanjude** [comment]
@gkwhite is this finished now?

**Comment by gkwhite** [comment]
yes, it is finished.  if sometime later any of the authors get back to me with papers or abstracts, I'll add them in.
