### ISSUE TITLE
Add talks from vBSDCon 2017

### ISSUE THREAD

**Issue by allanjude** [freebsd/freebsd-papers#37]
https://www.youtube.com/watch?v=mz8LjS-MnVI
https://www.youtube.com/watch?v=Vr_T5hFtyoM
https://www.youtube.com/watch?v=A41cDCE6pTc
https://www.youtube.com/watch?v=Yhoq5M3AUc0
https://www.youtube.com/watch?v=iqnyFp3rhlY
https://www.youtube.com/watch?v=YY_Fkxqy4fg
https://www.youtube.com/watch?v=nVJAsfgB7xY
https://www.youtube.com/watch?v=nVJAsfgB7xY
https://www.youtube.com/watch?v=-0s1bCzUx0Y
https://www.youtube.com/watch?v=0ke7p_Mh6Mg
https://www.youtube.com/watch?v=oqbUw8pxOJk

Bonus points if you badger the speakers to get the slides.

**Comment by allanjude** [comment]
@gkwhite is this finished now?

**Comment by gkwhite** [comment]
yes, it is finished.  if sometime later any of the authors get back to me with papers or abstracts, I'll add them in.
