### ISSUE TITLE
new version of hugo causes screwy menu

### ISSUE THREAD

**Issue by allanjude** [freebsd/freebsd-papers#54]
Upgrading hugo changed some things, and the menu is a bit screwy now, EuroBSDCon appears multiple times etc.

**Comment by ppaeps** [comment]
Things also look very strange on mobile devices: only half of the menu is visible, even with the device in landscape mode.  Do we know anyone who understands web development who wants to help us out with this? :)

**Comment by allanjude** [comment]
I have made a number of changes to the template so that conferences are no longer listed twice in the menu, or the landing pages.

I have also adjusted the CSS so only the year or conference you are looking at is expanded

**Comment by allanjude** [comment]
With 42efeb1a7d4c2006d94bd8fc1d45b7d79a87d9ae the site should render correctly on a phone. The menu is collapsed by default, with a 'navigation' button at the top of the screen, when you press it, it will open a menu that is usable on a mobile device.
