### ISSUE TITLE
Add talks from FreeBSD miniconf at linux.conf.au 2020

### ISSUE THREAD

**Issue by lwhsu** [freebsd/freebsd-papers#63]
https://linux.conf.au/schedule/#tuesday

https://www.youtube.com/watch?v=Hjpqa_kjCOI

**Comment by ppaeps** [comment]
Still missing slides from:

- [ ] [The other Unix-like operating system (Deb Goodkin)](https://linux.conf.au/schedule/presentation/180/)
- [ ] [LPI and BSD Working Together (Matt Rice](https://linux.conf.au/schedule/presentation/210/)
- [ ] [FreeBSD bhyve intro (Peter Grehan)](https://linux.conf.au/schedule/presentation/232/)

**Comment by debdrup** [comment]
I've reached out to grehan and mrice via email, so I should hopefully have the last two pdfs soon.

**Comment by ppaeps** [comment]
> I've reached out to grehan and mrice via email, so I should hopefully have the last two pdfs soon.

Thanks!  I prodded them in person before leaving the conference too.
