### ISSUE TITLE
Add talks from BSD devroom at FOSDEM 2020

### ISSUE THREAD

**Issue by lwhsu** [freebsd/freebsd-papers#64]
https://fosdem.org/2020/schedule/track/bsd/

**Comment by ppaeps** [comment]
After merging #70, we're stilling missing papers from:

- [ ] FreeBSD Around the World! (Deb Goodkin)
- [ ] KDE on FreeBSD (Adriaan De Groot)
- [ ] X11 and Wayland: A tale of two implementations (raichoo)

**Comment by lwhsu** [comment]
Do you think we should also include this one? https://fosdem.org/2020/schedule/event/early_unix/

**Comment by ppaeps** [comment]
Yes.  We should include Warner's talk since it likely had at least some BSD content (though I've not watched the video yet).

Were there any other BSD talks at the plenary conference or in other tracks?

**Comment by lwhsu** [comment]
raichoo's side is at https://acmelabs.space/~raichoo/fosdem/#1

**Comment by ppaeps** [comment]
> raichoo's side is at https://acmelabs.space/~raichoo/fosdem/#1

Thanks for the pointer!

**Comment by lwhsu** [comment]
We haven't added Warner's talk.

**Comment by ppaeps** [comment]
> We haven't added Warner's talk.

Whoops!  Sorry about that.  I just added the video and I've prodded warner about his slides.  I'll close this issue again when I get the slides.
