### ISSUE TITLE
FreeBSD Enterprise Storage at PBUG 2020/02

### ISSUE THREAD

**Issue by vermaden** [freebsd/freebsd-papers#73]
Hi,

I recently made **FreeBSD Enterprise Storage** presentation at the _Polish BSD User Group_.

Details here:
https://vermaden.wordpress.com/2020/02/12/freebsd-enterprise-storage-at-pbug/

Presentation is available here:
https://is.gd/bsdstg

... or a shorted 'unified' version here:
https://is.gd/bsdstguni

Do you think it will be valuable to add it to the **papers.freebsd.org** page?

Regards.

**Comment by allanjude** [comment]
Yes, I do.

Since it did not happen at an event where we have a number of other talks as well, just put it in the root of the 2020 directory (the attachments go in a subdirectory as explained in the readme)

**Comment by ppaeps** [comment]
This is an awesome presentation, @vermaden!  Please submit a pull request!

Was the talk recorded by any chance?

**Comment by vermaden** [comment]
Thank You.

It was recorded but and it will probably be available here on the PBUG channel [1] but it was recorded in Polish so I am not sure how useful that remains :)

[1] https://www.youtube.com/channel/UCWvDQaEHSULuCIVOOM66nYA/videos?view=0&sort=dd&flow=grid

I will try to make a pull request, if I fail then I will ask for your help :)

Regards.

**Comment by ppaeps** [comment]
Maybe include a "note: video is in Polish - slides are in English" in the talk description. ;-)

**Comment by ppaeps** [comment]
@vermaden *gently prodding*

Do you need help with this? ;-)

**Comment by vermaden** [comment]
Not sure, I failed at this step:

```
% git submodule init                                  
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by ppaeps** [comment]
You need to `git submodule init` after cd-ing to the clone.  You're probably still in the parent directory?

**Comment by vermaden** [comment]
Yes, that shines some light into the topic, I forgot the `git clone` step.

I have added mine changes (also added ZFS Boot Environments Reloaded from 2018) and I could now fork the repo, make pull request between repos etc. but IMHO it would be simpler and faster to just send you the changes I made.

Feel free to edit them as you wish.

Here is the changed/added content.

```
% pwd
/home/vermaden/freebsd-papers

% tar -czvf NEW.tar.gz \
  content/2018/NLUUG/_index.md \
  content/2018/NLUUG/vermaden-zfs-boot-environments-reloaded.files/nluug-zfs-boot-environments-reloaded-2018-11-15.pdf \
  content/2018/NLUUG/vermaden-zfs-boot-environments-reloaded.md \
  content/2020/'Polish BSD User Group'/_index.md \
  content/2020/'Polish BSD User Group'/vermaden-freebsd-enterprise-storage.files/vermaden-freebsd-enterprise-storage.pdf \
  content/2020/'Polish BSD User Group'/vermaden-freebsd-enterprise-storage.md \
```

Sorry for inconvenience.

[NEW.tar.gz](https://github.com/freebsd/freebsd-papers/files/4295124/NEW.tar.gz)

Regards.

**Comment by ppaeps** [comment]
Thanks for your submission! :pray:

I've committed both presentations with (very) minor changes.

**Comment by vermaden** [comment]
Thank you very much :)

Regards.
